#!/bin/bash

set -e
set -o pipefail

function msg    { echo -e "\E[${COLOR}m$@\E[0m" >&2 ; }
function notice { COLOR="0;36" msg "NOTICE: $@" ; }



notice 'Installing git and rubygems'

sudo apt-get update
sudo apt-get install --yes --force-yes git-core rubygems



notice 'Installing rake, puppet and librarian-puppet'

sudo gem install puppet librarian-puppet --no-ri --no-rdoc



notice 'Setting up puppet-git user'

PGRHOME=/var/lib/puppet-git-receiver
PGRUSER=puppet-git

sudo adduser --system --quiet --home "$PGRHOME" --no-create-home  --disabled-password --shell /usr/bin/git-shell --group "$PGRUSER"
sudo groupadd -f puppet

sudo mkdir -p $PGRHOME/.ssh
sudo cp /tmp/puppet-git-key $PGRHOME/.ssh/authorized_keys
sudo chmod 600 $PGRHOME/.ssh/authorized_keys
sudo chmod 750 $PGRHOME
sudo chown -R $PGRUSER.$PGRUSER $PGRHOME

echo 'puppet-git	ALL=NOPASSWD: SETENV:/usr/local/bin/puppet' | sudo tee /etc/sudoers.d/puppet-git-receiver
sudo chmod 0440 /etc/sudoers.d/puppet-git-receiver
sudo service sudo restart



notice 'Setting up git repository'

REPOPATH="$PGRHOME/puppet.git"
sudo mkdir -p $REPOPATH
HOOKSPATH=$REPOPATH/hooks/
if [ ! -d "$HOOKSPATH" ] ; then
  sudo git init --bare $REPOPATH
fi

sudo cp /tmp/git-post-update-hook $PGRHOME/git-post-update-hook
sudo ln -fns $PGRHOME/git-post-update-hook "${HOOKSPATH}post-update"
sudo chmod +x "${HOOKSPATH}post-update"

sudo chown -R $PGRUSER.$PGRUSER $REPOPATH
